# Python Homework (NumPy, Pandas)

### __Use markdown formatting for the following questions (e.g., bold lettering, bullet points, different font sizes, etc.):__


__1. What does Pandas stand for?__
1. Panel Data
2. Python Data Analysis

__2. What are the 2 collections used in Pandas?__
1. Series
2. DataFrame

__3. Name 4 things Pandas can do for us.__
1. Manipulate
2. Prepare
3. Model
4. Analyze

__4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?__
- inplace=True

__5. What is a CSV?__
- CSV stands for Comma-Seperated Values and is a plain text file format commonly used for storing tabular data.

__6. When cleaning data what values do we not like our data.__
- Null values





__7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()__

In [84]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

reshapedArray = array.reshape(2, 3, 2)

reshapedArray

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

__8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20__

In [43]:
array = np.linspace(0, 20, 6)

array

array([ 0.,  4.,  8., 12., 16., 20.])

__9. Make a Deep Copy of the above array__

In [44]:
array_copy = array.copy()

array_copy

array([ 0.,  4.,  8., 12., 16., 20.])

__10. Concatenate these 3 arrays into a new array named 'newArray'...__

In [45]:
ar1 = np.array([[25, 16]])
ar2 = np.array([[11, 2], [13, 4]])
ar3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((ar1, ar2, ar3))

newArray

array([[25, 16],
       [11,  2],
       [13,  4],
       [ 7, 81],
       [ 5,  6],
       [11, 12]])

__11. Sort 'newArray' in order into 'sortedArray'__

In [46]:
sortedArray = np.sort(newArray)

sortedArray

array([[16, 25],
       [ 2, 11],
       [ 4, 13],
       [ 7, 81],
       [ 5,  6],
       [11, 12]])

__12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.__

In [54]:
var1, var2, var3, var4 = reshapedArray[0][0], reshapedArray[0][1], reshapedArray[1][0], reshapedArray[1][1]

print(var1)
print(var2)
print(var3)
print(var4)

[1 2]
[3 4]
[7 8]
[ 9 10]


__13. Combined and sort the following arrays into one called 'comboArray' ...__   
    one = ([10, 11, 12, 13, 14, 15, 16, 17])  
    two = ([20, 21, 22, 23, 24, 25, 26, 27])  
    three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

In [70]:
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = one + two + three
comboArray.sort()
print(comboArray)



[0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]


__14. Take 'comboArray' and perform the following slicing activities:__

In [72]:
sec1 = comboArray[1]
sec2 = comboArray[2:]
sec3 = comboArray[3:14]
sec4 = comboArray[-6:]
sec5 = comboArray[:16]
sec6 = comboArray[20::2]
sec7 = comboArray[::-5]

print("sec1:", sec1)
print("sec2:", sec2)
print("sec3:", sec3)
print("sec4:", sec4)
print("sec5:", sec5)
print("sec6:", sec6)
print("sec7:", sec7)

sec1: 1
sec2: [2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]
sec3: [3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15]
sec4: [22, 23, 24, 25, 26, 27]
sec5: [0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17]
sec6: [24, 26]
sec7: [27, 22, 15, 10, 3]


__15. Using Series, create a DataFrame that looks like this:__  
Ingredients	Quantity	Unit  
Flour	        4	    cups  
Milk	        1	    cup  
Eggs	        2	    large  
Spam	        1	    can  

In [102]:
import pandas as pd

ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name = 'Ingredients')
quantity = pd.Series([4, 1, 2, 1], name = 'Quantity')
unit = pd.Series(['cups', 'cup', 'large', 'can'], name = 'Unit')

df = pd.concat([ingredients, quantity, unit], axis=1)

print(df)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


__16. Take this data and create a DataFrame named studentData__  
    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],  
        'Height': [5.1, 6.2, 5.1, 5.2],  
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],  
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],  
        'Age': [21, 23, 24, 21],  
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],  
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']  
    }


In [91]:
students = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'Address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
studentData = pd.DataFrame(students)

print(studentData)

      Name  Height Qualification  Address  Age        Pets           Sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


__17. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]__

In [93]:
studentData["Desserts"] = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

__18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"__

In [95]:
studentData.sort_values(['Name'], ascending= True)

Name  Height Qualification  Address  Age        Pets           Sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       desserts      Desserts  
3  Carrot Halwa  Carrot Halwa  
2       waffels       waffels  
0     ice cream     ice cream  
1  Cashew Fudge  Cashew Fudge

In [96]:
studentData.sort_values(['Address'], ascending= True)

Name  Height Qualification  Address  Age        Pets           Sport  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       desserts      Desserts  
2       waffels       waffels  
3  Carrot Halwa  Carrot Halwa  
0     ice cream     ice cream  
1  Cashew Fudge  Cashew Fudge

__19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:__  
    df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

In [98]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')

__20.  
(A) Using Pandas, make your own .CSV file with data on vegetables and save it.__

In [104]:
import pandas as pd

vegetable = pd.Series(['Broccoli', 'Cucumber', 'Turnip', 'Peas'], name = 'Vegetable')
color = pd.Series(['Green', 'Yellow', 'Purple', 'Green' ], name = 'Color')


df = pd.concat([vegetable, color], axis=1)

df.to_csv('vegetables.csv')


print(df)

  Vegetable   Color
0  Broccoli   Green
1  Cucumber  Yellow
2    Turnip  Purple
3      Peas   Green


__20.  
(B) Using Pandas, make a change to your CSV file, and save a copy with a different name.__

In [105]:
vegetablesNew = pd.read_csv('vegetables.csv')

goodBad = pd.Series(['Good', 'Bad', 'Bad', 'Good'])

df2 = pd.concat([df, goodBad])

df2.to_csv('vegetables2.csv')